### ISSUE TITLE
[Help] Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`

### ISSUE THREAD

**Issue by sacredMonster** [browserslist/browserslist#259]
Hello,
I am using **css-loader@0.28.11** with webpack in my project and when I try to build my project for production, I get the following error:

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader!./stylesheets/main.scss
2018-05-10T19:37:00.6214094Z Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
2018-05-10T19:37:00.6214460Z     at error (..\node_modules\browserslist\index.js:37:11)
2018-05-10T19:37:00.6214663Z     at ..\node_modules\browserslist\index.js:222:9
2018-05-10T19:37:00.6214874Z     at Array.forEach (native)
2018-05-10T19:37:00.6214994Z     at browserslist (..\node_modules\browserslist\index.js:196:13)
2018-05-10T19:37:00.6215144Z     at cleanBrowsersList (..\node_modules\caniuse-api\dist\utils.js:56:59)
2018-05-10T19:37:00.6215329Z     at setBrowserScope (..\node_modules\caniuse-api\dist\index.js:29:43)
2018-05-10T19:37:00.6215472Z     at Object.<anonymous> (..\node_modules\caniuse-api\dist\index.js:91:1)
2018-05-10T19:37:00.6215589Z     at Module._compile (module.js:570:32)
2018-05-10T19:37:00.6215801Z     at Object.Module._extensions..js (module.js:579:10)
2018-05-10T19:37:00.6215944Z     at Module.load (module.js:487:32)
2018-05-10T19:37:00.6216040Z     at tryModuleLoad (module.js:446:12)
2018-05-10T19:37:00.6216136Z     at Function.Module._load (module.js:438:3)
2018-05-10T19:37:00.6216233Z     at Module.require (module.js:497:17)
2018-05-10T19:37:00.6216365Z     at require (internal/module.js:20:19)
2018-05-10T19:37:00.6216504Z     at Object.<anonymous> (..\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:7:19)
2018-05-10T19:37:00.6216630Z     at Module._compile (module.js:570:32)
2018-05-10T19:37:00.6216771Z     at Object.Module._extensions..js (module.js:579:10)
2018-05-10T19:37:00.6216869Z     at Module.load (module.js:487:32)
2018-05-10T19:37:00.6216962Z     at tryModuleLoad (module.js:446:12)
2018-05-10T19:37:00.6217058Z     at Function.Module._load (module.js:438:3)
2018-05-10T19:37:00.6217197Z     at Module.require (module.js:497:17)
2018-05-10T19:37:00.6217292Z     at require (internal/module.js:20:19)
2018-05-10T19:37:00.6217416Z     at Object.<anonymous> (..\node_modules\postcss-merge-rules\dist\index.js:21:28)
2018-05-10T19:37:00.6217575Z     at Module._compile (module.js:570:32)
2018-05-10T19:37:00.6217676Z     at Object.Module._extensions..js (module.js:579:10)
2018-05-10T19:37:00.6217774Z     at Module.load (module.js:487:32)
2018-05-10T19:37:00.6218000Z     at tryModuleLoad (module.js:446:12)
2018-05-10T19:37:00.6218144Z     at Function.Module._load (module.js:438:3)
2018-05-10T19:37:00.6218373Z     at Module.require (module.js:497:17)
2018-05-10T19:37:00.6218478Z     at require (internal/module.js:20:19)
2018-05-10T19:37:00.6261552Z  @ ./stylesheets/main.scss 4:14-111
2018-05-10T19:37:00.6261795Z  @ ./index.jsx
```
I have not explicitly included any browserlist config file in my project.

Thanks,
Karina

**Comment by ai** [comment]
O_o seems like you have some problem with webpack config. Ask webpack team.

**Comment by sacredMonster** [comment]
I will go ahead and file a help ticket on webpack meanwhile here is my webpack config (the same for both dev and prod):
```
const webpack = require('webpack');
const path = require('path');

const BUILD_DIR = path.resolve(__dirname, 'dist');
const APP_DIR = path.resolve(__dirname, '');

const webConfig = env => ({
  entry: `${APP_DIR}/index.jsx`,
  output: {
    path: BUILD_DIR,
    filename: 'myfile.js',
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  module: {
    rules: [
      {
        test: /\.jsx?/,
        include: APP_DIR,
        exclude: /node_modules/,
        loaders: ['babel-loader', 'eslint-loader'],
      },
      {
        test: /\.scss$/,
        include: APP_DIR,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
      },
      {
        test: /\.(woff|woff2|ttf|eot|svg)(\?v=[a-z0-9]\.[a-z0-9]\.[a-z0-9])?$/,
        loader: 'url-loader?limit=100000',
      },
    ],
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        BUILD_BUILDNUMBER: JSON.stringify(process.env.BUILD_BUILDNUMBER),
        NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development'),
      },
    }),
  ],
});

module.exports = webConfig;
```
thanks...

**Comment by ai** [comment]
Config looks correct. Try to grep `basedir=` in your project.

**Comment by sacredMonster** [comment]
Did a grep and found **`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`** in a lot of node_modules eg:
`node_modules\.bin\browserslist:2:basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`

**Comment by ai** [comment]
Hm, so maybe it is not a problem of webpack.

Seems like you have some conflict between npm and your operating system.

1. Try to remove `node_modules/` and install it again. Maybe you get `node_modules` from different OS.
2. Do you use Windows, Linux or Mac?
3. If you use Windows, do you have Git or Cygwin on your system?

**Comment by LeTo34** [comment]
I have the same problem. Did you find a solution ? Thanks for your help

**Comment by ojhadiwesh** [comment]
So were you guys able to figure out if this was a webpack issue or a npm OS conflict?

**Comment by vansosnin** [comment]
It's some OS issue, as I can judge. But I didn't find out the reason. Somehow Windows OS tries to run _shell_ script instdead of _.cmd_ for browserslist.

Workaround worked for me:
1. Find path where npm global scripts are stored, like this (screenshot from SO):
![image](https://user-images.githubusercontent.com/8207551/215055818-e0a8172d-a8fc-42a5-b4c3-67e2b8b94bf0.png)
2. Remove or rename files `browserlist` and `browserslist` (I think only 1 right would be enough but I don't want to find which is right). I just added symbol `_` to the end of the filename.

And it worked.

My requisites just in case if someone want to dig it deeper:
OS: MS Windows 10
Node: v16.15.1

**Comment by juanger** [comment]
In my case, the problem was that an old version of `npm` was installing the shims in the root directory of my package. When browserslist tries to read configuration files (because webpack tries to find the default `target`) it finds the UNIX shim, treating it as a configuration, that's why you see those expressions in the error message, because it is a shell command that was mistakenly parsed as a configuration.

I didn't confirm which browserslist version can fix it, but I see that the configuration parsing code added validation in newer versions of browserslist.

My fix was just to update npm to a newer version.

In my case I was not even using a browserslist configuration file, I pass the configuration programatically at a later time, but webpack forces browserslist to try resolving the config files to add defaults.
