### ISSUE TITLE
BrowserslistError: Unknown version 11 of Node.js

### ISSUE THREAD

**Issue by deepkolos** [browserslist/browserslist#310]
error
```
D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:692
          throw new BrowserslistError(
          ^
BrowserslistError: Unknown version 11 of Node.js
    at Function.select (D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:692:17)
    at D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:144:33
    at Array.reduce (<anonymous>)
    at resolve (D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:125:18)
    at Function.select (D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:715:14)
    at D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:144:33
    at Array.reduce (<anonymous>)
    at resolve (D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:125:18)
    at browserslist (D:\DEV\Github\work\feng-bbs-mobile\node_modules\browserslist\index.js:222:16)
    at cleanBrowsersList (D:\DEV\Github\work\feng-bbs-mobile\node_modules\caniuse-api\dist\utils.js:59:59)
    at setBrowserScope (D:\DEV\Github\work\feng-bbs-mobile\node_modules\caniuse-api\dist\index.js:26:43)
    at Object.<anonymous> (D:\DEV\Github\work\feng-bbs-mobile\node_modules\caniuse-api\dist\index.js:88:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

cfg
```
# Browsers that we support
# https://browserl.ist/

last 3 years
> 1%
maintained node versions
not dead
```

**Comment by crusoexia** [comment]
@deepkolos  I have the same issue. What do you mean 'node-releases data outdated'?

**Comment by ai** [comment]
@crusoexia check `npm ls` and find `node-releases `1.0.0-beta…` versions. If you have it, you need to update your npm dependencies.
