### ISSUE TITLE
BrowserslistError: Unknown browser query `cover 99.9%`

### ISSUE THREAD

**Issue by darrencoen** [browserslist/browserslist#337]
> postcss ./site/templates/styles/*.css --use autoprefixer -d ./site/templates/styles/ --map

× Processing site\templates\styles\main.css
{ BrowserslistError: Unknown browser query `cover 99.9%`
    at C:\PATH_REDACTED\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (C:\PATH_REDACTED\node_modules\browserslist\index.js:132:18)
    at browserslist (C:\PATH_REDACTED\node_modules\browserslist\index.js:224:16)
    at Browsers.parse (C:\PATH_REDACTED\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (C:\PATH_REDACTED\node_modules\autoprefixer\lib\browsers.js:52:30)
    at loadPrefixes (C:\PATH_REDACTED\node_modules\autoprefixer\lib\autoprefixer.js:70:24)
    at plugin (C:\PATH_REDACTED\node_modules\autoprefixer\lib\autoprefixer.js:81:24)
    at LazyResult.run (C:\PATH_REDACTED\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (C:\PATH_REDACTED\node_modules\postcss\lib\lazy-result.js:192:32)
  name: 'BrowserslistError',
  message: 'Unknown browser query `cover 99.9%`',
  browserslist: true }

	"dependencies": {
		"autoprefixer": "^7.2.6",
		"postcss-cli": "^4.1.1"
	}

**Comment by ai** [comment]
@dangreen update Autoprefixer and `postcss-cli` to fix this issue.

you use *very* old Autoprefixer and PostCSS CLI. They use very old Browserslist which doesn’t support this query.
