### ISSUE TITLE
Consider not writing to stderr or allowing opt-out

### ISSUE THREAD

**Issue by wbinnssmith** [browserslist/browserslist#361]
It's a bit surprising to have a library [write to stderr as a side effect of invoking it](https://github.com/browserslist/browserslist/blob/master/node.js#L307):

> Browserslist: caniuse-lite is outdated. Please run next command yarn upgrade caniuse-lite browserslist

Perhaps `browserlist` could also accept a callback that it would yield warning messages to.

I definitely understand the reasoning behind these warnings, but tools using browserslist may have their own command line interfaces that would be disrupted by it writing to stderr. In this case it would be best to have the tool decide how to surface this feedback.

If it's still absolutely necessary to write to stderr, perhaps a default implementation would do so, but if the library was invoked with an `onWarn` or similar, it would not.

**Comment by ai** [comment]
> I definitely understand the reasoning behind these warnings, but tools using browserslist may have their own command line interfaces that would be disrupted by it writing to stderr

I thought about this case, this is why I write to `stderr` instead of `stdout`.

Tell me more about your case, let’s find the best option here (just disabling warning will keep users to use old Can I Use data, but I understand your problem and will try to find the best solution to fit all problems).

**Comment by lisaweathers** [comment]
i have no ideal what i am doing, yes i need help lol , i need to fix some issues

**Comment by ai** [comment]
@lisaweathers what issues do you have?

**Comment by lisaweathers** [comment]
Hi andrey, i need to speed up computer, i do not knw anything about
computers, it says i need to render, javascript mininzing and css, i am lost

**Comment by ai** [comment]
@lisaweathers since it is not related to this issue, you should not describe it here.

I can give you some advice, just write to me to andrey@sitnik.ru and give more details about. What do you do with a computer? What type of computer? What exactly action is slow.

**Comment by wbinnssmith** [comment]
Thanks for the reply @ai. Our use case is pretty close to what I described: in @parcel-bundler we invoke @babel/preset-env which uses `browserslist`. We have a rich cli interface[1] implemented with @vadimdemedes/ink, which relies on control of stdio. We currently patch console.log to avoid browserlist from writing directly to stderr.

[1] https://github.com/parcel-bundler/parcel/blob/v2-work-so-far/packages/reporters/cli/src/CLIReporter.js#L13

**Comment by ai** [comment]
@wbinnssmith why you can’t update `caniuse-lite` in this use case?

**Comment by ai** [comment]
@wbinnssmith I can add `BROWSERSLIST_IGNORE_OLD_DATA=true` environment variable for this case

**Comment by wbinnssmith** [comment]
Fantastic. Thank you so much 😃

**Comment by ai** [comment]
Done 0ae7155

**Comment by ai** [comment]
Released in 4.5.4

**Comment by OsuperSunny** [comment]
Please I have been running scan on source code and keep getting error saying analysis fail. Please what should I do
?. See Error Details:
java.lang.IllegalStateException: Unrecoverable indexation failures: 1 errors among 1 requests
	at org.sonar.server.es.IndexingListener$1.onFinish(IndexingListener.java:39)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:131)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.doIndex(ProjectMeasuresIndexer.java:162)
	at org.sonar.server.measure.index.ProjectMeasuresIndexer.indexOnAnalysis(ProjectMeasuresIndexer.java:87)
	at org.sonar.ce.task.projectanalysis.step.IndexAnalysisStep.execute(IndexAnalysisStep.java:45)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeStep(ComputationStepExecutor.java:81)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:72)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:59)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:212)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:194)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:160)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:135)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:87)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


Also, I notice that this keeps showing in my scan process 
each time I scan: 

ERROR: Browserslist: caniuse-lite is outdated. Please run:
ERROR: npx browserslist@latest --update-db
ERROR:
ERROR: Why you should do it regularly:
ERROR: https://github.com/browserslist/browserslist#browsers-data-updating
