### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.

### ISSUE THREAD

**Issue by akshayakrsh** [browserslist/browserslist#382]
```BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.```

I received this error when using the `react-starter-app`, maybe its got to do something with `BrowsersList` itself, hence reporting it here.

**Comment by silverwind** [comment]
Same error, my `browserslist` does not actually contain a `android all`, where does it come from?

**Comment by SathyaThangam** [comment]
BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)
    at new Promise 

> (<anonymous>)

even I received the same error during deployment

**Comment by lkiarest** [comment]
Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.

**Comment by zhipenglin** [comment]
Same issue

**Comment by TonSDe** [comment]
I have same issue. and can't run "yarn dev" or "yarn run build" in Nuxt-app.

**Comment by Desyon** [comment]
Having the same issue

**Comment by solonik1** [comment]
Same issue

**Comment by meliksu** [comment]
Same issue

**Comment by iwangx** [comment]
Same issue

**Comment by micooz** [comment]
Same issue :)

**Comment by NoureldeanSaed** [comment]
Same issue

**Comment by pawelrol** [comment]
Same issue

**Comment by hileix** [comment]
Same issue.

**Comment by rajjejosefsson** [comment]
have the issue when using postcss-preset-env using rollup, seems create-react-app uses this too

**Comment by keyurbhole** [comment]
Same Issue

**Comment by ranabhat** [comment]
Same issue 
```
{ BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:204:10)
    at /home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:296:11
    at Array.reduce (<anonymous>)
    at resolve (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:237:18)
    at browserslist (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/browserslist/index.js:361:16)
    at browserslist (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:92:24)
    at Array.some (<anonymous>)
    at some (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:91:32)
    at Array.filter (<anonymous>)
    at filter (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss-preset-env/src/postcss.js:90:43)
    at creator (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/postcss/lib/postcss.es6:111:34)
    at config.plugins.sortPlugins.map (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4168:18)
    at Array.map (<anonymous>)
    at PostcssConfig.loadPlugins (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4162:10)
    at PostcssConfig.config (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4198:14)
    at StyleLoader.postcss (/home/OCPP-tester-ElifTech/ocpp-tester-masterv2/ocpp-tester/node_modules/@nuxt/webpack/dist/webpack.js:4255:39)
  name: 'BrowserslistError',
  message:
   'Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.',
  browserslist: true }

```

**Comment by honghui-qiao** [comment]
Same issue, please fix it ASAP

**Comment by HansJiang** [comment]
Same issue @ben-eb 
![image](https://user-images.githubusercontent.com/11820468/59665134-e90c9e00-91e4-11e9-9017-c8ed26d044bd.png)

**Comment by huynd8295** [comment]
Same for me, surprised that alot of people is facing this issue

**Comment by hshettigar444** [comment]
Same Issue

**Comment by piro0919** [comment]
Same Issue

**Comment by delias** [comment]
Same Issue

**Comment by quoctoank4it** [comment]
same issue

**Comment by EricFung** [comment]
Same Issue , my project run well yestoday   T.T

**Comment by FinalAngel** [comment]
pin ``"caniuse-lite": "1.0.30000974"`` in your ``package.json``

**Comment by Pradeep-DCPL** [comment]
Same Issue

BrowserslistError: Unknown browser query android all. Maybe you are using old Browserslist or made typo in query.
at Array.reduce ()
at Array.some ()
at Array.filter ()

**Comment by needfortri** [comment]
Same issue using Nuxt

FATAL  Unknown browser query android all. Maybe you are using old Browserslist or made typo in query.

  at unknownQuery (node_modules/browserslist/index.js:204:10)
  at node_modules/browserslist/index.js:296:11
  at Array.reduce (<anonymous>)
  at resolve (node_modules/browserslist/index.js:237:18)
  at browserslist (node_modules/browserslist/index.js:361:16)
  at supportedBrowsers.some.supportedBrowser (node_modules/postcss-preset-env/index.js:438:105)
  at Array.some (<anonymous>)
  at stagedFeatures.filter.feature (node_modules/postcss-preset-env/index.js:438:80)
  at Array.filter (<anonymous>)
  at postcss$1.plugin.opts (node_modules/postcss-preset-env/index.js:438:44)
  at creator (node_modules/postcss/lib/postcss.js:133:35)
  at config.plugins.sortPlugins.map (node_modules/@nuxt/webpack/dist/webpack.js:4128:18)
  at Array.map (<anonymous>)
  at PostcssConfig.loadPlugins (node_modules/@nuxt/webpack/dist/webpack.js:4122:10)
  at PostcssConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4158:14)
  at StyleLoader.postcss (node_modules/@nuxt/webpack/dist/webpack.js:4215:39)

**Comment by palashmon** [comment]
Quick fix for now, remove development browserlist items in package.json:

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": []
  }
```

**Comment by ai** [comment]
There is no query `X all` in Browserslist.

Report issue to `react-starter-app` they have wrong query.

**Comment by lkiarest** [comment]
Maybe it's the problem of caniuse-lite,  I remove all the installed packages and reinstall last version of it then the error is fixed..
```
yarn add caniuse-lite@1.0.30000974
```

**Comment by ckristhoff** [comment]
> Maybe it's the problem of caniuse-lite, I remove all the installed packages and reinstall last version of it then the error is fixed..
> 
> ```
> yarn add caniuse-lite@1.0.30000974 --dev
> ```

It works for me. Better solution for now.

**Comment by ai** [comment]
@ikiarest we never supported `android all` query.

**Comment by mohammadsobhy** [comment]
delete these lines in the package json file
"last 1 chrome version",
"last 1 firefox version",
"last 1 safari version",
"Android >= 4"
an its worked

**Comment by Albinzr** [comment]
Is there any proper solution for this?

**Comment by Veerpool** [comment]
no one not working with nuxt :(

**Comment by ai** [comment]
There is an issue in Nuxt. They do something wrong and use query which we never support.

**Comment by Albinzr** [comment]
@mohammadsobhy  **"Android >= 4"** is also not working

**Comment by buschtoens** [comment]
@ai I can confirm that forcing a yarn resolution for `caniuse-lite@1.0.30000974` fixes the error. It must be an issue with the latest `caniuse-lite@1.0.30000975` release.

**Comment by Veerpool** [comment]
`There is an issue in Nuxt. They do something wrong and use query which we never support.`
How it can issue in Nuxt, if everything be ok, no one update and fail. 
and you have a lot of issue there =) ok)

**Comment by ai** [comment]
> It must be an issue with the latest caniuse-lite@1.0.30000975 release.

I think Can I Use update just opened a bug in Nuxt. We never support `andoid all` query.

**Comment by mathiastm** [comment]
i have same issue

**Comment by Veerpool** [comment]
> There is an issue in Nuxt. They do something wrong and use query which we never support.

Yes, you are right. Found a problem with 2 packet

**Comment by ai** [comment]
Seems like the issue related with `postcss-preset-env`. It is always in stack trace.

**Comment by buschtoens** [comment]
@ai It's `postcss-preset-env`, which in turn uses `cssdb` to load the `polyfillableFeatures`, which in turn uses `caniuse-lite`. It is very likely caused by the latest `caniuse-lite` update.

**Comment by ai** [comment]
@buschtoens can you test what is inside `feature` where `polyfillableFeatures` was callled?

**Comment by EricFung** [comment]
[root@iZ2ze3bv8i4oxkd7w8r2c5Z front]# npm run build

> front@0.1.0 build /root/wr/example/front
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/styles.module.css
BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the front@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-18T08_53_17_354Z-debug.log

**Comment by Anima-t3d** [comment]
> pin `"caniuse-lite": "1.0.30000974"` in your `package.json`
> 
> they released a new version 2 hours ago:
> https://www.npmjs.com/package/caniuse-lite

This did not work for me, using nuxt 2.8.1

**Comment by albertleigh** [comment]
add resolutions to depending app package.json for a temp quick fix

```
 "resolutions": {
    "caniuse-lite": "1.0.30000974"
  }
``

**Comment by mtikmani** [comment]
Error, Same :(

**Comment by Veerpool** [comment]
>  "resolutions": {
>     "caniuse-lite": "1.0.30000974"
>   }

that is only for yarn

**Comment by ai** [comment]
I released a very dirty fix in Browserslist 4.6.3. Try to update.

**Comment by ai** [comment]
Subscribe to https://twitter.com/browserslist for recent news about this issue

**Comment by pratiknesarkar99** [comment]
** Install the Caniuse-lite from here*** This works fine
https://www.npmjs.com/package/caniuse-lite**

**Comment by pimlie** [comment]
@ai Yes thanks, now it just prints a gazillion warnings ;)

**Comment by MartinBalerio** [comment]
> I released a very dirty fix in Browserslist 4.6.3. Try to update.

As mentioned by @albertleigh the issue is with the [caniuse-lite](https://www.npmjs.com/package/caniuse-lite/v/1.0.30000975) new version, resolutions fix the issue with yarn and `npm install caniuse-lite@1.0.30000974 --save-dev --save-exact` fixes the issue with NPM for now.

**Comment by ai** [comment]
> Yes thanks, now it just prints a gazillion warnings ;)

The warnings is a payment for dirty fix (we need a real fix and warnings will force us to create it)

**Comment by MartinBalerio** [comment]
@ai I guess we delete our comments?

**Comment by Veerpool** [comment]
Thanks it is Works

**Comment by needfortri** [comment]
@ai I'm now able to build with nuxt without changing config.
Just got the warning "WARN  BrowserslistError: Unknown browser query android all" a hundred times during compilation, but once app is deployed everything seems to work fine.
Thanks a lot !

**Comment by ai** [comment]
@MartinBalerio the right solution is to update to Browserslist 4.6.3. Locking Can I use will create more problems.

**Comment by timoken** [comment]
It's not a browserlist problem. The error comes from here https://github.com/ben-eb/caniuse-lite/issues/27

**Comment by MartinBalerio** [comment]
@ai got it, thanks!

**Comment by pi0** [comment]
![image](https://user-images.githubusercontent.com/5158436/59670028-72fe3c00-91d0-11e9-9526-6a6ae98a43ef.png) (SPOLER: 4x more)

@ai Is this a right solution? :thinking: 

Agree that locking is not really a good idea but maybe `browserlist` can silently ignore and hide this warning until `caniuse-lite` or `browserslist` releases proper fix?

**Comment by 974N** [comment]
I got the same issue when trying to run my react app through vscode terminal.

Failed to compile
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
BrowserslistError: Unknown browser query `android all`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at Array.some (<anonymous>)
    at Array.filter (<anonymous>)

**Comment by Aukhan** [comment]
updating to `4.6.3` works with warnings, hopefully the real fix comes from caniuse-lite

**Comment by Rockshox93** [comment]
How can i get the dirty fix? I'm all new to this, so please be serious 😆

**Comment by pimlie** [comment]
@Rockshox93 remove `yarn.lock` or `package-lock.json`, remove `node_modules` and run npm/yarn install again

**Comment by ai** [comment]
> updating to 4.6.3 works with warnings, hopefully the real fix comes from caniuse-lite

The real fix should be in postcss-preset-env or in some library which it uses

**Comment by delias** [comment]
"dependencies": {
    "caniuse-lite": "^1.0.30000975",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "browserslist": "4.6.3"
  }

npm update
npm start
Worked for me

**Comment by ai** [comment]
> Agree that locking is not really a good idea but maybe browserlist can silently ignore and hide this warning until caniuse-lite or browserslist releases proper fix?

If Browserslist will ignore it silently the real fix will be written free month later. I know how open source works.

Also ignoring `android all` means that we can miss some prefixes for Android browser. It is a dirty did, Browserslist output is still incorrect (because wrong input was sent into it).

**Comment by AlexLevus** [comment]
"browserslist": {
"production": [
">0.2%",
"not dead",
"not op_mini all"
],
"development": [
]
}
Update to your package.json . it worked for me as well.

**Comment by wsv587** [comment]
I received the same error. And I use yarn install instead of npm isntall, yarn run start instead of num start. that is OK!

**Comment by FrankGnanamuttu** [comment]
npm i browserslist 

worked for me

**Comment by Rockshox93** [comment]
> 
> 
> @Rockshox93 remove `yarn.lock` or `package-lock.json`, remove `node_modules` and run npm/yarn install again

@pimlie it worked, thanks mate 😄

**Comment by b593771943** [comment]
> "dependencies": {
> "caniuse-lite": "^1.0.30000975",
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "react-scripts": "3.0.1",
> "browserslist": "4.6.3"
> }
> 
> npm update
> npm start
> Worked for me
Good job~

**Comment by b593771943** [comment]
> "dependencies": {
> "caniuse-lite": "^1.0.30000975",
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "react-scripts": "3.0.1",
> "browserslist": "4.6.3"
> }
> 
> npm update
> npm start
> Worked for me

Also worked~

**Comment by b593771943** [comment]
> npm i browserslist
> 
> worked for me
before one hour, It can't work. but now worked

**Comment by wsv587** [comment]
I received the same error. And I use yarn install instead of npm isntall, yarn run start instead of npm start. that is OK!
Maybe, cause the developer of my team used yarn for package.

**Comment by b593771943** [comment]
> I received the same error. And I use yarn install instead of npm isntall, yarn run start instead of npm start. that is OK!
> Maybe, cause the developer of my team used yarn for package.

It has nothing to do with yarn，maybe the author did something~

**Comment by R1ON** [comment]
> "dependencies": {
> "caniuse-lite": "^1.0.30000975",
> "react": "^16.8.6",
> "react-dom": "^16.8.6",
> "react-scripts": "3.0.1",
> "browserslist": "4.6.3"
> }
> 
> npm update
> npm start
> Worked for me

Thanks, it's worked ))

**Comment by oodmumc3** [comment]
@AlexLevus 
work for me! thanks!!

**Comment by MrToxy** [comment]
updating node to v12.1.0 and this issue does happen anymore

**Comment by ssjsatish** [comment]
@R1ON this worked for me for command `npm run build`

Thanks

**Comment by paramsinghvc** [comment]
WTF, this issue has eaten up my whole day. Still, I'm struggling to run my app with this stinking thing. Any help would be appreciated.

**Comment by ai** [comment]
> Still, I'm struggling to run my app with this stinking thing. Any help would be appreciated.

Call `yarn upgrade` or `npm update`

**Comment by stevepop** [comment]
I am getting the same ` WARN  BrowserslistError: Unknown browser query android all` warning today since I upgraded to Nuxt v2.8.0. Any fix to get rid of this warning?

**Comment by ai** [comment]
@stevepop 

> I am getting the same WARN BrowserslistError: Unknown browser query android all warning today since I upgraded to Nuxt v2.8.0. Any fix to get rid of this warning?

You will have this warning until we will not have the real fix in `postcss-preset-env`. Here are reasons for these warnings: https://github.com/browserslist/browserslist/issues/382#issuecomment-503029523

**Comment by MrToxy** [comment]
also I've noticed that with yarn this issue doesn't arrise

**Comment by nazboost** [comment]
I have same issue when I use https://github.com/hiroppy/fusuma/.
How to solve `BrowserslistError: Unknown browser query `android all``?

**Comment by ryicoh** [comment]
> I have same issue when I use https://github.com/hiroppy/fusuma/.
How to solve BrowserslistError: Unknown browser query 'android all'?
updating to `4.6.3`
specifically, run this command
```
npm i browserslist@4.6.3
```

**Comment by chepkasoff** [comment]
Still getting this
`BrowserslistError: Unknown browser query `android all`` 100500x times in the console.

**Comment by FrancisVarga** [comment]
same here still getting the problem

**Comment by ai** [comment]
@chepkasoff warning is a trade-off of current dirty fix. The warning will gone when postcss-preset-env maintenaner will wake up and make the real solution

@FrancisVarga do you have warning or error? Did you update Browserslist? How did you try to update npm dependencies?

**Comment by SobakaSlava** [comment]
@ai thank you for dirty fix, now it's only a warning, but is the problem really in `postcss-preset-env`? It seems like `postcss-preset-env` is using `caniuse-lite` which was updated by you a few hours ago. Isn't the problem there?

**Comment by ai** [comment]
@SobakaSlava postcss-preset-env has a code to generate browsers list accounting to selected features.

With fresh Can I Use data (Android browser was marked that it supported something new) it started to add non-existed `android all` browser.

The problem is with this browsers list generation.

**Comment by gson88** [comment]
@AlexLevus Your solution fixed the logging issue but it created more styling problems in our dev environment instead.

**Comment by gregorwebmaster** [comment]
updat ```caniuse-lite``` to "1.0.30000974" fixed the problem for me.

**Comment by molszanski** [comment]
it seems like `caniuse-lite` has unpublished the bad version. `rm -rf node_modules` and reinstall deps

**Comment by tarreislam** [comment]
i hate npm

**Comment by alex-lechner** [comment]
@gregorwebmaster for now, this solved it for me, thanks!

**Comment by deot** [comment]
thanks!
1. `npm cache clean --force`
2. `rm -rf node_modules package-lock.json yarn.lock && npm install`
3. `npm install caniuse-lite@1.0.30000974`

**Comment by vinhlh** [comment]
`1.0.30000975` doesn't work 💃

**Comment by ycjcl868** [comment]
temporary solution:

```json
// package.json

  "resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  },
```

**Comment by lichunshan** [comment]
> temporary solution:
> 
> ```json
> // package.json
> 
>   "resolutions": {
>     "browserslist": "4.6.2",
>     "caniuse-lite": "1.0.30000974"
>   },
> ```

This method solved my problem.

**Comment by lijukrks** [comment]
> updat `caniuse-lite` to "1.0.30000974" fixed the problem for me.

This seems works for me , thanks

**Comment by FrancisVarga** [comment]
So when this gonna resolve without temporary fix?

**Comment by 974N** [comment]
@AlexLevus your solution saved my app thanks !

**Comment by wbern** [comment]
For pnpm users, see this pnpmfile.js

```javascript
function readPackage(packageJson, context) {
...
        case 'browserslist':
            packageJson.dependencies['caniuse-lite'] = '1.0.30000974';
            break;
...
```

**Comment by testcderick** [comment]
Do we have some alternative package of postcss-preset-env?

**Comment by ai** [comment]
@testcderick nope. Nobody wants to do CSS tools in the current world when authors of CSS tools don’t have followers and community support.

**Comment by testcderick** [comment]
Thanks @ai

**Comment by joseferrer1090** [comment]
@akshayakrsh hellow men !!!

Hello, I have precisely the same error, and I solved it but I have my app in production on a ubuntu server version 16.04 !!!

1- The first thing you have to see is the version of nodejs in your place and I recommend that you update it to the more stable version

2- the second thing you have to do in your package.json verify the brorserlist section, in my case leave that section empty.

3- The third thing you have to do after you update the version of your nodejs on your server, assign root permission

4- delete the node_modules folder together with the build => remember that it is created in a corrupt way !!!

5- If everything goes well rewrite this line in the package json "browserslist": [
    "> 0.2%",
    "not dead",
    "not ie <= 9",
    "not op_mini all"
  ]

Good Luck !!!!

**Comment by JaneMax** [comment]
> ```
> npm i browserslist@4.6.3
> ```
That is made the `npm start` compilation successful but error left: **BrowserslistError: Unknown browser query `android all`**

**Comment by ai** [comment]
@JaneMax do `npm update` to update Browserslist inside dependency tree

**Comment by jonathantneal** [comment]
I have posted this in other threads, but I will share it here as well:

---

It looks like `caniuse` or `caniuse-lite` may have published a potentially breaking change that rolled into `postcss-preset-env`, which then rolled into `browserslist` and threw this error or warning.

**How it worked**: More or less, caniuse stats are provided as an object of features, like `{ "css-all": {}, "css-any-link": {} }`. Within each feature, stats are provided as an object of browsers, like `{ "android": {}, "edge": {} }`. Within each browser, stats are provided as an object of versions or version ranges, like `{ 4.1": "n", "4.2-4.3": "n" }`.

For example, one tree of features might look like `{ "css-all": { "android": { "4.1": "n", "4.2-4.3": "n" } } }`.

**What changed**: Within the `android` browser object of versions, stats now provide a simplified `"all"` value.

This means one tree of features might look like `{ "css-all": { "android": { "all": "n" } } }`.

That is how the `android all` query ends up getting generated, which browserslist does not support.

**Comment by ogbanana** [comment]
I had this same issue until I added the Browser Global Scripts to my index.html file. 

`<script src="https://unpkg.com/react/umd/react.production.js" crossorigin />

<script
  src="https://unpkg.com/react-dom/umd/react-dom.production.js"
  crossorigin
/>

<script
  src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
  crossorigin
/>

<script>var Alert = ReactBootstrap.Alert;</script>`

**Comment by shobishani** [comment]
I have same issue.
`  "browserslist": [
    "last 1 version",
    "> 1%",
    "IE 10"
  ],`

This is my `browserslist` query when i try `npx browserslist` it returns You made typo in browseslist.
I even tried with "defaults" but still won't work.

**Comment by jasper-seinhorst** [comment]
I've had the same issue. My fix was to add the dependancy: "postcss-preset-env" (Latest) to my packge.json. I noticed that a dependancy of a dependancy used an older version. With the failing query. Adding it as dev dependancy worked for me

**Comment by shobishani** [comment]
@jasper-seinhorst Sure I'll try that as well.

**Comment by shobishani** [comment]
Removing browserlist from dependency and then adding the last version `4.6.2` with the 
`"resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  },`  
then reinstall
 `yarn add browserlist@4.6.2`
 worked for me. Thanks @jasper-seinhorst @ycjcl868

**Comment by testcderick** [comment]
Builds is okay now, since the latest update to caniuse-lite from 5 hours ago.

Update the version of caniuse 1.0.30000976 and everything will be fine.

**Comment by jimblue** [comment]
Can't wait for the new Browserlist release 😓

**Comment by ai** [comment]
@jimblue what do you need from new release?

**Comment by jonathantneal** [comment]
@jimblue, since the break and the fix both occurred in a patch releases of caniuse-db, you don’t need a new release. You just get the fix the next time your dependencies are updated, the same way you got the break.

**Comment by joseferrer1090** [comment]
Hola me paso lo mismo, la solucion que entonces fue ir al package.json, browserlist[ ], pero deja la version en las dependencias !!!

**Comment by jimblue** [comment]
> @jimblue what do you need from new release?

sorry I tough caniuse had to be update in browserlist...

**Comment by adelinyshka** [comment]
> > temporary solution:
> > ```json
> > // package.json
> > 
> >   "resolutions": {
> >     "browserslist": "4.6.2",
> >     "caniuse-lite": "1.0.30000974"
> >   },
> > ```
> 
> This method solved my problem.

for me works only like this:

// package.json

```
  "devDependencies": {
    "pug-loader": "^2.4.0",
    "browserslist": "4.6.2"
  },
  "resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  }
```

**Comment by sam77sakib** [comment]
> > updat `caniuse-lite` to "1.0.30000974" fixed the problem for me.
> 
> This seems works for me , thanks

can you please tell me how to update it?

**Comment by shobishani** [comment]
@sam77sakib You need to update the package.json 
update `"browserslist": "4.6.2"`
and add this 
`"resolutions": {
    "browserslist": "4.6.2",
    "caniuse-lite": "1.0.30000974"
  }`

remove node_modules and package-loc.json or yarn.lock if you are using yarn. 
then yarn install. it will be fixed.

**Comment by shobishani** [comment]
Even in create-react-app have this problem now.

**Comment by alaindimabuyo** [comment]
I have the same problem when I am creating a production build

**Comment by SagarBajpai** [comment]
Update the version of browserslist to 

> browserslist@4.6.2 along with caniuse-lite to 

> caniuse-lite@1.0.30000974 . It will Solve the problem. Add this 

> "resolutions": {
>     "browserslist": "4.6.2",
>     "caniuse-lite": "1.0.30000974"
>   }
to package.json file

**Comment by crllrd** [comment]
npm install caniuse-lite@1.0.30000974

This solution help me

**Comment by adpace-dt** [comment]
I ran into this issue and realized that I was typing "npx browserlist" instead of "npx browserslist" (plural). This resolved the issue.

**Comment by ycjcl868** [comment]
same issue using node 14
