### ISSUE TITLE
loadQueries require.resolve breaks eslint in VS Code when using sharable configs

### ISSUE THREAD

**Issue by benpink** [browserslist/browserslist#396]
Appreciate this is obscure and likely more of an eslint issue but is there any reason for the `require.resolve` in `loadQueries` to be scoped to the current path?:
https://github.com/browserslist/browserslist/blob/master/node.js#L116

I discovered that a path resolve within loadQueries causes eslint within VS Code to break in my (nested monorepo) project when using an extended sharable config. Removing the `paths` constraint fixes it:

```diff
- var queries = require(require.resolve(name, { paths: ['.'] }))
+ var queries = require(require.resolve(name))
```

Full stacktrace (with paths redacted):
```
[Error - 11:49:26 PM] ESLint stack trace:
[Error - 11:49:26 PM] Error: Error while loading rule 'compat/compat': Cannot find module 'browserslist-config-google'
Occurred while linting foo.jsx
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.loadQueries (/node_modules/browserslist/node.js:116:35)
    at Function.select (/node_modules/browserslist/index.js:951:26)
    at /node_modules/browserslist/index.js:255:33
    at Array.reduce (<anonymous>)
    at resolve (/node_modules/browserslist/index.js:237:18)
    at browserslist (/node_modules/browserslist/index.js:361:16)
    at DetermineTargetsFromConfig (/node_modules/eslint-plugin-compat/lib/Versioning.js:31:36)
    at Object.create (/node_modules/eslint-plugin-compat/lib/rules/compat.js:52:85)
```

**Comment by ai** [comment]
If I remember it correctly, I used `path` to avoid resolving path from `browserslist/` dir path.

We can change it if you will die that in different cases you did will work correctly (sorry, I will have 10+ hours flight and will need your help in investigation here).

**Comment by benpink** [comment]
Thanks @ai. It's not a huge problem for me right now (I can fork/work around it). I'll take another look at whether it is something I can overcome with VS Code / eslint config settings.

Closing ticket - I'll update if I find anything useful.
