### ISSUE TITLE
Unknown version 76 of edge

### ISSUE THREAD

**Issue by Beraliv** [browserslist/browserslist#489]
Hey,

After updating babel, prettier and browserslist I found an error while building the project

We have .browserslist-es2017 file like:

```
[es2017]
edge >= 16
...
unreleased edge versions
...
```

We get browsers like that:

```ts
const browsers = browserslist(undefined, {
    config: path.join(__dirname, './.browserslist-es2017'),
    env: 'es2017',
});
```

The list has edge versions as follows:

[..., **edge 76,edge 18,edge 17,edge 16**,...]

Here you see `edge 76`

The error started while processing: "node_modules/@babel/preset-env/lib/index.js"

```
at Function.select (node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:1086:17)
        at node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:336:33
        at Array.reduce (<anonymous>)
        at resolve (node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:318:18)
        at browserslist (node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:443:21)
        at getTargets (node_modules/@babel/helper-compilation-targets/lib/index.js:202:48)
        at _default (node_modules/@babel/preset-env/lib/index.js:246:57)
        at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
        at node_modules/@babel/core/lib/config/full.js:199:14
        at Generator.next (<anonymous>)
```

More information:

1. I tried last version of babel and browserslist, it fails as well
2. Current versions in `package.json` are

```
"devDependencies": {
    "@babel/core": "7.9.0",
    "@babel/plugin-proposal-class-properties": "7.8.3",
    "@babel/plugin-proposal-decorators": "7.8.3",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.8.3",
    "@babel/plugin-proposal-numeric-separator": "7.8.3",
    "@babel/plugin-proposal-optional-chaining": "^7.9.0",
    "@babel/plugin-transform-object-assign": "7.8.3",
    "@babel/plugin-transform-runtime": "7.9.0",
    "@babel/preset-env": "7.9.5",
    "@babel/preset-react": "7.9.4",
    "@babel/preset-typescript": "7.9.0",
    "@babel/runtime": "7.9.2",
   ...
   "browserslist": "4.9.1",
  ...
}
```

3. I checked that in `"@babel/preset-env": "7.9.5"` version of `browserslist` is `"^4.9.1"` so 4.9.1 should be a fit, but it's not

4. It might have similar problem as the comment which describes it - https://github.com/parcel-bundler/parcel/issues/1036#issuecomment-387887471

**Comment by ai** [comment]
Do you have different `caniuse-lite` versions in `npm ls`?

**Comment by Beraliv** [comment]
@ai 

It's a dependency for other dependencies, however yes, we have an outdated version

```
├─┬ @storybook/preact@5.3.14
│ └─┬ @storybook/core@5.3.14
│   ├─┬ @babel/preset-env@7.6.3
│   │ └─┬ browserslist@4.6.1
│   │   └── caniuse-lite@1.0.30001005 
│   ├─┬ autoprefixer@9.7.4
│   │ ├─┬ browserslist@4.8.6
│   │ │ └── caniuse-lite@1.0.30001027  deduped
│   │ └── caniuse-lite@1.0.30001027 
│   └─┬ react-dev-utils@9.1.0
│     └─┬ browserslist@4.7.0
│       └── caniuse-lite@1.0.30001027 
├─┬ browserslist@4.12.0
│ └── caniuse-lite@1.0.30001046 
├─┬ cssnano@4.1.8
│ └─┬ cssnano-preset-default@4.0.7
│   ├─┬ postcss-colormin@4.0.3
│   │ └─┬ browserslist@4.6.1
│   │   └── caniuse-lite@1.0.30001005  deduped
│   ├─┬ postcss-merge-longhand@4.0.11
│   │ └─┬ stylehacks@4.0.3
│   │   └─┬ browserslist@4.6.1
│   │     └── caniuse-lite@1.0.30001005  deduped
│   ├─┬ postcss-merge-rules@4.0.3
│   │ ├─┬ browserslist@4.6.1
│   │ │ └── caniuse-lite@1.0.30001005  deduped
│   │ └─┬ caniuse-api@3.0.0
│   │   ├─┬ browserslist@4.6.1
│   │   │ └── caniuse-lite@1.0.30001005 
│   │   └── caniuse-lite@1.0.30000890 
│   ├─┬ postcss-minify-params@4.0.2
│   │ └─┬ browserslist@4.6.1
│   │   └── caniuse-lite@1.0.30001005  deduped
│   ├─┬ postcss-normalize-unicode@4.0.1
│   │ └─┬ browserslist@4.6.1
│   │   └── caniuse-lite@1.0.30001005  deduped
│   └─┬ postcss-reduce-initial@4.0.3
│     └─┬ browserslist@4.6.1
│       └── caniuse-lite@1.0.30001005  deduped
├─┬ postcss-preset-env@6.6.0
│ ├─┬ autoprefixer@9.6.0
│ │ ├─┬ browserslist@4.7.2
│ │ │ └── caniuse-lite@1.0.30001005  deduped
│ │ └── caniuse-lite@1.0.30001005 
│ ├─┬ browserslist@4.6.1
│ │ └── caniuse-lite@1.0.30001005 
│ └── caniuse-lite@1.0.30001002 
└─┬ postcss-variables-loader@5.0.2
  └─┬ postcss-cssnext@3.1.0
    ├─┬ autoprefixer@7.2.6
    │ ├─┬ browserslist@2.11.3
    │ │ └── caniuse-lite@1.0.30001012 
    │ └── caniuse-lite@1.0.30001012 
    ├─┬ caniuse-api@2.0.0
    │ └── caniuse-lite@1.0.30000890 
    └─┬ pixrem@4.0.1
      └─┬ browserslist@2.11.3
        └── caniuse-lite@1.0.30001012 
```

In yarn.lock we have that:

```
caniuse-lite@^1.0.0:
  version "1.0.30000890"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30000890.tgz#86a18ffcc65d79ec6a437e985761b8bf1c4efeaf"

caniuse-lite@^1.0.30000792, caniuse-lite@^1.0.30000805:
  version "1.0.30001012"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001012.tgz#653ec635e815b9e0fb801890923b0c2079eb34ec"
  integrity sha512-7RR4Uh04t9K1uYRWzOJmzplgEOAXbfK72oVNokCdMzA67trrhPzy93ahKk1AWHiA0c58tD2P+NHqxrA8FZ+Trg==

caniuse-lite@^1.0.30000939:
  version "1.0.30001002"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001002.tgz#ba999a737b1abd5bf0fd47efe43a09b9cadbe9b0"
  integrity sha512-pRuxPE8wdrWmVPKcDmJJiGBxr6lFJq4ivdSeo9FTmGj5Rb8NX3Mby2pARG57MXF15hYAhZ0nHV5XxT2ig4bz3g==

caniuse-lite@^1.0.30000971, caniuse-lite@^1.0.30001004:
  version "1.0.30001005"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001005.tgz#823054210be638c725521edcb869435dae46728d"
  integrity sha512-g78miZm1Z5njjYR216a5812oPiLgV1ssndgGxITHWUopmjUrCswMisA0a2kSB7a0vZRox6JOKhM51+efmYN8Mg==

caniuse-lite@^1.0.30000989, caniuse-lite@^1.0.30001020, caniuse-lite@^1.0.30001023:
  version "1.0.30001027"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001027.tgz#283e2ef17d94889cc216a22c6f85303d78ca852d"
  integrity sha512-7xvKeErvXZFtUItTHgNtLgS9RJpVnwBlWX8jSo/BO8VsF6deszemZSkJJJA1KOKrXuzZH4WALpAJdq5EyfgMLg==

caniuse-lite@^1.0.30001043:
  version "1.0.30001046"
  resolved "http://storage.mds.yandex.net/get-npm/1891400/caniuse-lite-1.0.30001046.tgz#7a06d3e8fd8aa7f4d21c9a2e313f35f2d06b013e"
  integrity sha512-CsGjBRYWG6FvgbyGy+hBbaezpwiqIOLkxQPY4A4Ea49g1eNsnQuESB+n4QM0BKii1j80MyJ26Ir5ywTQkbRE4g==
```

How can I get which version suits us?

**Comment by Beraliv** [comment]
If I understand right

1. Only `caniuse-lite@1.0.30000890` is deprecated here
2. It's located in two branches:

  * first

```
└─┬ postcss-variables-loader@5.0.2
  └─┬ postcss-cssnext@3.1.0
    └─┬ caniuse-api@2.0.0
      └── caniuse-lite@1.0.30000890 
```

  * second

```
└─┬ cssnano@4.1.8
  └─┬ cssnano-preset-default@4.0.7
    └─┬ postcss-merge-rules@4.0.3
      └─┬ caniuse-api@3.0.0
        └── caniuse-lite@1.0.30000890 
```

I think I should have a try to update them all

**Comment by ai** [comment]
@Beraliv we have a special helper to update all `caniuse-lite` dependencies:

```
npx browserslist@latest --update-db
```

**Comment by Beraliv** [comment]
> npx browserslist@latest --update-db

Thank you for the help, it works

**Comment by ai** [comment]
If Yandex wants to support Russian open source, you can tell your manager about our Open Collective

https://opencollective.com/browserslist

**Comment by wangpin34** [comment]
> @Beraliv we have a special helper to update all `caniuse-lite` dependencies:
> 
> ```
> npx browserslist@latest --update-db
> ```

Still got the issue `Unknown version 87 of edge`.
