### ISSUE TITLE
can't run npx browserslist --update-db on windows

### ISSUE THREAD

**Issue by chanan** [browserslist/browserslist#535]
When I run the command: `npx browserslist --update-db` on windows I get: `Cannot read property '1' of null`

I made sure I updated to the latest: `browserslist@4.14.2`

**Comment by ai** [comment]
Try `npx browserslist@latest --update-db`

If it will not help post the full error message (I need file names and line numbers).

**Comment by chanan** [comment]
Yes that worked, thanks!

**Comment by DavidHenri008** [comment]
@ai  I am getting this error too:
```
PS C:\Git\web-lib-dglux-widget> npx browserslist@latest --update-db
C:\Git\web-lib-dglux-widget\node_modules\autoprefixer\node_modules\browserslist\update-db.js:49
    if (match[1]) return match[1]
             ^

TypeError: Cannot read property '1' of null
    at getCurrentVersion (C:\Git\web-lib-dglux-widget\node_modules\autoprefixer\node_modules\browserslist\update-db.js:49:14)
    at updateDB (C:\Git\web-lib-dglux-widget\node_modules\autoprefixer\node_modules\browserslist\update-db.js:119:17)
    at Object.<anonymous> (C:\Git\web-lib-dglux-widget\node_modules\autoprefixer\node_modules\browserslist\cli.js:40:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by ai** [comment]
@DavidHenri008 open another issue, please. Seems like you have a problem not relevant to this one.

**Comment by DavidHenri008** [comment]
I just fixed the issue by clearing my node-modules and my lock file. Thanks.
