### ISSUE TITLE
An unhandled exception occurred: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query

### ISSUE THREAD

**Issue by hardy21** [browserslist/browserslist#540]
Hi, 
I receive this error when doing an angular build after recently upgraded from Angular v5 to v9. The package.json file contains the browserslist query (I simplified it to see if that helped):
`  "browserslist": [
    "defaults"
  ]
`

In an attempt to make it work I also set the latest version in the dependencies section:
`    "browserslist": "^4.14.5",
    "caniuse-lite": "1.0.30001135"`

What's interesting is that the angular build works fine in Windows 10 (local) but fails in Linux Rhel 7 (remote). Here is the full error:

[error] BrowserslistError: Unknown browser query `var fs = require('fs')`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/browserslist/index.js:285:10)
    at /nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/browserslist/index.js:372:11
    at Array.reduce (<anonymous>)
    at resolve (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/browserslist/index.js:318:18)
    at browserslist (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/browserslist/index.js:443:21)
    at cleanBrowsersList (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/caniuse-api/dist/utils.js:59:59)
    at setBrowserScope (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/caniuse-api/dist/index.js:26:43)
    at Object.<anonymous> (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/caniuse-api/dist/index.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/nif/builds/bamboo/agent_0006/xml-data/build-dir/SER-REV23-JOB1/angular-src/node_modules/postcss-reduce-initial/dist/index.js:17:19)

I'm out of clues on how to fix this error, hope to get some help here. Thanks!

**Comment by ai** [comment]
Somebody sends a wrong query to Browserslist.

Try to walkthrough stacktrace and find who send `var fs = require('fs')` to Browserslist.

There is nothing I can help from Browserslist side.

**Comment by ai** [comment]
Other options:

1. Move to `.browserslistrc` config
2. Try to use environment variable instead of config: `BROWSERSLIST=defaults npm build` (put your build script here)

**Comment by ai** [comment]
You may also try to update dependencies by `npm update` (or `yarn update`) to be sure that you are used the latest versions (maybe it was a bug, which was fixed).

**Comment by ai** [comment]
And last option is to go to `node_modules` for each line in stacktrace, read sources around lines from stacktrace.

You should find something like `browserslist(string, { … })`.

Then try to put `console.log(string)` (or what variable will they use) to find where that JS code came from.

**Comment by hardy21** [comment]
Thanks a lot for the answers! All these are good options. However, I had someone from another team look at my build configuration and found something wrong with the way I had setup the working subdirectory (in Bamboo). So probably the browserslist configuration I mentioned above was never even read.
