### ISSUE TITLE
browserlist.coverage fail with custom coverage file

### ISSUE THREAD

**Issue by danylkaaa** [browserslist/browserslist#607]
Hello! I tried to use your snippet to get coverage when querying my custom stats.

```javascript
// process.env.BROWSERSLIST_STATS === path.join(__dirname, './browserslist-stats.json');
const browsers = browserslist();
browserslist.coverage(browsers, 'my stats')
```

But I get this error

```
TypeError: Cannot read property 'op_mini' of undefined
    at normalizeStats (<...>/node_modules/browserslist/node.js:127:11)
    at Object.getStat (<...>/node_modules/browserslist/node.js:209:12)
    at Function.browserslist.coverage (<....>/node_modules/browserslist/index.js:580:27)
```

I found that it is caused by this 3f54ebd[/index.js#L580](https://github.com/browserslist/browserslist/blob/3f54ebdf5d2160ab74b42ead2bd695b3864bf31a/index.js#L580) :

```javascript
// node_modules/browserslist/index.js:580
var customStats = env.getStat(opts)
```

Which calls `getStat()` from `browserslist/node.js` 

3f54ebd[`/node.js#L209`](https://github.com/browserslist/browserslist/blob/3f54ebdf5d2160ab74b42ead2bd695b3864bf31a/node.js#L209)

```
  getStat: function getStat (opts, data) {
    // some ops, but "data" argument is not overrided
    return normalizeStats(data, stats) // <- data is undefined
  }
```

And then browserlist tries to access the data members w/o checking that the `data` exists.

3f54ebd[/node.js#L127](https://github.com/browserslist/browserslist/blob/3f54ebdf5d2160ab74b42ead2bd695b3864bf31a/node.js#L127)

```javascript
if (
      versions.length === 1 &&
      data[i] && // <- raises error
      data[i].versions.length === 1
    )
```

So, I considered to add extra check

```

function normalizeStats (data, stats) {
  if (!data) {
    data = {};
  }
  //...
}
```

**Comment by danylkaaa** [comment]
Also I created PR #608 with my proposed changes
