### ISSUE TITLE
BrowserslistError: Unknown browser query `supports es6-module`. Maybe you are using old Browserslist or made typo in query.

### ISSUE THREAD

**Issue by Frostbourn** [browserslist/browserslist#635]
I received this error when using the latest release of gatsby, maybe it's got to do something with BrowsersList itself. Before the upgrade from Gatsby 3.2.0 everything was working smooth. Even if I use the latest `browserslist` and `caniuse-lite`:

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
BrowserslistError: Unknown browser query supports es6-module. Maybe you are using old Browserslist or made typo in query.
```

When I run `npx browserslist@latest --update-db` the `caniuse-lite` is gone from `package.json`:
```
Latest version:     1.0.30001269
Installed version:  none
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
$ yarn remove -W caniuse-lite
caniuse-lite has been successfully updated

No target browser changes
```

**Comment by ai** [comment]
Strange that you have `Installed version:  none`. What version of Browserslist do you use (`npm ls | grep browserslist`)?

**Comment by BojanKogoj** [comment]
Any idea which dependency was the issue? I'm having same issue when updating Angular from 14 to 15 (and I'm [not alone](https://github.com/angular/angular-cli/issues/24212))

```
[error] BrowserslistError: Unknown browser query `supports es6-module`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (projectpath\node_modules\browserslist\index.js:201:10)
    at projectpath\node_modules\browserslist\index.js:288:11
    at Array.reduce (<anonymous>)
    at resolve (projectpath\node_modules\browserslist\index.js:234:18)
    at browserslist (projectpath\node_modules\browserslist\index.js:353:16)
    at projectpath\node_modules\@schematics\angular\migrations\update-15\remove-browserslist-config.js:76:37
    at async callRuleAsync (projectpath\node_modules\@angular-devkit\schematics\src\rules\call.js:78:18)
```

I have `browserslist@4.21.4`
