### ISSUE TITLE
`--update-db` fails with "Your cache folder contains root-owned files"

### ISSUE THREAD

**Issue by rooselle** [browserslist/browserslist#686]
Hello !

I'm attempting to run `npx browserslist@latest --update-db` but it fails with following error:
```bash
{
  "error": {
    "code": "EACCES",
    "summary": "\nYour cache folder contains root-owned files, due to a bug in\nprevious versions of npm which has since been addressed.\n\nTo permanently fix this problem, please run:\n  sudo chown -R 1000:1000 \"/root/.npm\"",
    "detail": ""
  }
}

node:child_process:905
    throw err;
    ^

Error: Command failed: npm show caniuse-lite --json
{
  "error": {
    "code": "EACCES",
    "summary": "\nYour cache folder contains root-owned files, due to a bug in\nprevious versions of npm which has since been addressed.\n\nTo permanently fix this problem, please run:\n  sudo chown -R 1000:1000 \"/root/.npm\"",
    "detail": ""
  }
}


    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at getLatestInfo (/var/www/html/node_modules/browserslist/update-db.js:52:18)
    at updateDB (/var/www/html/node_modules/browserslist/update-db.js:202:16)
    at Object.<anonymous> (/var/www/html/node_modules/browserslist/cli.js:40:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 243,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(290) [Uint8Array] [
      123,  10,  32,  32,  34, 101, 114, 114, 111, 114,  34,  58,
       32, 123,  10,  32,  32,  32,  32,  34,  99, 111, 100, 101,
       34,  58,  32,  34,  69,  65,  67,  67,  69,  83,  34,  44,
       10,  32,  32,  32,  32,  34, 115, 117, 109, 109,  97, 114,
      121,  34,  58,  32,  34,  92, 110,  89, 111, 117, 114,  32,
       99,  97,  99, 104, 101,  32, 102, 111, 108, 100, 101, 114,
       32,  99, 111, 110, 116,  97, 105, 110, 115,  32, 114, 111,
      111, 116,  45, 111, 119, 110, 101, 100,  32, 102, 105, 108,
      101, 115,  44,  32,
      ... 190 more items
    ]
  ],
  pid: 415,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(290) [Uint8Array] [
    123,  10,  32,  32,  34, 101, 114, 114, 111, 114,  34,  58,
     32, 123,  10,  32,  32,  32,  32,  34,  99, 111, 100, 101,
     34,  58,  32,  34,  69,  65,  67,  67,  69,  83,  34,  44,
     10,  32,  32,  32,  32,  34, 115, 117, 109, 109,  97, 114,
    121,  34,  58,  32,  34,  92, 110,  89, 111, 117, 114,  32,
     99,  97,  99, 104, 101,  32, 102, 111, 108, 100, 101, 114,
     32,  99, 111, 110, 116,  97, 105, 110, 115,  32, 114, 111,
    111, 116,  45, 111, 119, 110, 101, 100,  32, 102, 105, 108,
    101, 115,  44,  32,
    ... 190 more items
  ]
}
```

I've run command `sudo chown -R 1000:1000 /root/.npm` with success, I even deleted the `.npm` folder but I'm still getting the issue. It seems that it could be a problem with `npx`, after reading #675. However, unlike the author of this issue I'm using npm, thus I cannot run `yarn dlx`.

Is there an alternative way of running `browserslist@latest --update-db` command?

NPM version 8.6.0

**Comment by ai** [comment]
You can use:

1. Run `npm update` to update all dependencies
2. Use `package.resolution` https://www.wisdomgeek.com/development/web-development/javascript/overriding-nested-dependencies-in-npm/
3. Move to pnpm. pnpm has a good built-in tool to update indirect dependency `pnpm up caniuse-lite`.
4. Manually remove all `caniuse-lite` from lock file and then call `npm install caniuse-lite` in your project.

How to test the result:
1. Get the latest published version from https://www.npmjs.com/package/caniuse-lite
2. Open your lock file and look for all `caniuse-lite` version
3. They should be the latest version
