### ISSUE TITLE
Browserslist update fails with "TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by jayKayEss** [browserslist/browserslist#726]
We update browserslist as part of our CI build spec. Today the update started failing with the following error (console output from running manually on my Mac, but this is also failing on CI under Linux with the same error.)

```
jks@Auton speedchainr2 %  npx browserslist@latest --update-db
Need to install the following packages:
  browserslist@4.21.3
Ok to proceed? (y) y
Latest version:     1.0.30001390
/Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:135
      versions[match[1]] = true
                    ^

TypeError: Cannot read properties of null (reading '1')
    at /Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:135:21
    at Array.forEach (<anonymous>)
    at updateYarnLockfile (/Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:132:10)
    at updateLockfile (/Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:164:12)
    at updatePackageManually (/Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:171:22)
    at updateDB (/Users/jks/SpeedChain/speedchainr2/node_modules/update-browserslist-db/index.js:268:5)
    at Object.<anonymous> (/Users/jks/SpeedChain/speedchainr2/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/cli.js:42:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

Here is our config from `package.json`:

```
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 3 safari version"
        ]
    },
```

Running `npx browserslist-lint` doesn't turn up any issues.

**Comment by ai** [comment]
What package manager do you use? (and what version)?

**Comment by ai** [comment]
Try also new command `npx update-browserslist-db@latest`

**Comment by jayKayEss** [comment]
> What package manager do you use? (and what version)?

I think CI is configured to always use the latest `yarn`... I'm running `1.22.19` on my Mac too.

`2022-09-06T20:05:10.842Z [INFO]: # Done patching NPM package 'yarn' to version 1.22.19`

**Comment by jayKayEss** [comment]
> Try also new command `npx update-browserslist-db@latest`

This is working on CI now (after updating our build image to use node 16 from 14.) Thanks!
