### ISSUE TITLE
`--update-db` fails on yarn

### ISSUE THREAD

**Issue by Danon** [browserslist/browserslist#742]
```
PS C:\Users\Daniel\WebstormProjects\4play> yarn browserslist --update-db
yarn run v1.22.19
$ C:\Users\Daniel\WebstormProjects\4play\node_modules\.bin\browserslist --update-db
'npx' is not recognized as an internal or external command,
operable program or batch file.                            
Latest version:     1.0.30001441                           
Installed version:  1.0.30001441                           
caniuse-lite is up to date                                 
caniuse-lite has been successfully updated                 
                                                           
Error: Command failed: npx browserslist                    
'npx' is not recognized as an internal or external command,
operable program or batch file.                            

    at checkExecSyncError (node:child_process:871:11)
    at Object.execSync (node:child_process:943:15)
    at getBrowsersList (C:\Users\Daniel\WebstormProjects\4play\node_modules\browserslist\update-db.js:62:6)
    at updateDB (C:\Users\Daniel\WebstormProjects\4play\node_modules\browserslist\update-db.js:322:23)
    at Object.<anonymous> (C:\Users\Daniel\WebstormProjects\4play\node_modules\browserslist\cli.js:43:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)

Problem with browser list retrieval.
Target browser changes won’t be shown.
Done in 0.68s.
PS C:\Users\Daniel\WebstormProjects\4play> 
```

It would appear browser list in method `getBrowsersList()` calls itself using `npx`, but it fails on systems without `npx`.

**Comment by ai** [comment]
What Node.js version do you use?

**Comment by Danon** [comment]
@ai `18.12.1`

**Comment by ai** [comment]
Why don't you have `npx`? It should be part of Node.js.

**Comment by Danon** [comment]
@ai I decided to use `yarn` for all my projects.

**Comment by ai** [comment]
Of course, but `npm` is part of Node.js as I understand

**Comment by Danon** [comment]
@ai You can use `node` without `npm` or `corepack` just fine. `npm` is just a package manager, and `yarn` works just fine.

**Comment by ai** [comment]
Just found that this issue was already fixed.

Please update `browserslist` to the latest version.
