### ISSUE TITLE
Version compatibility issues

### ISSUE THREAD

**Issue by c0deCn** [browserslist/browserslist#760]
I'm currently using vue 2 + webpack 4 (a rather outdated configuration)

Now I have a problem: when "browserslist": [ "> 1%", "last 2 versions" ], an error occurs when a package is introduced

When set to

"browserslist": [ "defaults and supports es6-module", "maintained node versions" ].

When the error is fixed, the error is resolved, but the callback for async.queue mapLimit etc. is gone. Please ask the gods how to achieve a compatible solution

**Comment by ai** [comment]
What error do you have exactly?

**Comment by c0deCn** [comment]
> 
if browserslist": [ "> 1%", "last 2 versions" ], the
The error is:
TypeError: Cannot convert a BigInt value to a number
at Math.pow (<anonymous>)
at SWUFpSqrtRatio (weierstrass.ts:1097:1)
at mapToCurveSimpleSWU (weierstrass.ts:1166:1)
at eval (secp256k1.ts:249:1)
at ./node_modules/_@noble_curves@1.0.0@@noble/curves/secp256k1.js (chunk-vendors.js:15341:1)
at __webpack_require__ (app.js:854:30)
When set to "browserslist": [ "defaults and supports es6-module", "maintained node versions" ]. The error is resolved, but the callbank functions for methods such as async.queue mapLimit are gone on our system, and we are currently looking for a compatible solution that will allow us to get our system running without massive changes

**Comment by ai** [comment]
The stacktrace came not from Browserslist. Seems like it is a bundler or webapp issue. Browserslist config changes just enable some polyfill which broke or fix thing.
